jQuery(function($){
    $.scrollTo(0);
    $('.scrollup').click(function(){
        $.scrollTo($('#AboutMe'),1000);
    });
})
jQuery(function($){
    $.scrollTo(0);
    $('.Skills').click(function(){
        $.scrollTo($('#skills'),1000);
    });
})
jQuery(function($){
    $.scrollTo(0);
    $('.projects').click(function(){
        $.scrollTo($('#projects'),1000);
    });
})
jQuery(function($){
    $.scrollTo(0);
    $('.contact').click(function(){
        $.scrollTo($('#Contact'),1000);
    });
})
